//This is normal for loop
console.log("This is generated by normal for loop.");
    let sum = 0; //initialization
    for (let i = 0; i <= 10; i++) {
        sum += i;
    }
    console.log("Sum of natural numbers from 0 to 10 is ", sum); 
    // Output: Sum of natural numbers from 0 to 10 is 55



//This is a while loop
console.log("This is generated by while loop.");

let n = 0;

while (n < 3) {
  n++;
}

console.log(n);
// Expected output: 3



//This is a do-while loop
console.log("This is generated by do-while loop.");

let result = '';
let k = 0;

do {
  k = k + 1;
  result = result + k;
} while (k < 5);

console.log(result);
// Expected output: "12345"



//this is for-of loop
console.log("This is generated by for-of loop.");
    let str = "TanmayBagul";

    for (let i of str) {
        console.log("i = ", i);
    }
    // Output: i =  T
    //         i =  a
    //         i =  n
    //         i =  m
    //         i =  a
    //         i =  y
    //         i =  b
    //         i =  a
    //         i =  g
    //         i =  u
    //         i =  l


// //we can use this loop for arrays also
console.log("This is loop also used for arrays.");
    let arr = [1, 2, 3, 4, 5];

    for (let i of arr) {
        console.log("i = ", i);
    }

    // Output: i =  1
    //         i =  2
    //         i =  3
    //         i =  4
    //         i =  5

